# Generated by Django 4.2.2 on 2023-07-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_appointment_start_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='state',
            field=models.CharField(choices=[('O', 'Open'), ('B', 'Booked'), ('NA', 'Not Available')], default='O', max_length=2),
        ),
    ]
