# Generated by Django 4.2.2 on 2023-07-05 19:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=256, null=True)),
                ('model', models.CharField(max_length=256, null=True)),
                ('year', models.CharField(max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('transmission', models.CharField(choices=[('A', 'Automatic'), ('M', 'Manual')], max_length=1, null=True)),
                ('fuel_type', models.CharField(choices=[('D', 'Diesel'), ('G', 'Gasoline'), ('H', 'Hybrid'), ('E', 'Electric')], max_length=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('driving_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='userProfile.userprofile')),
            ],
        ),
    ]
