# Generated by Django 4.2.2 on 2023-07-05 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userProfile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivingSchool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary')], max_length=1, null=True)),
                ('type', models.CharField(choices=[('I', 'Instructor'), ('S', 'Student')], max_length=1, null=True)),
                ('address', models.CharField(default='', max_length=254)),
                ('postal_code', models.CharField(max_length=8, null=True)),
                ('location_city', models.CharField(default='', max_length=254)),
                ('country', models.CharField(choices=[('CH', 'Switzerland'), ('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy')], max_length=2, null=True)),
                ('about', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=userProfile.models.user_directory_path)),
                ('instructor_license', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('has_learner_permit', models.BooleanField(blank=True, default=False, null=True)),
                ('phone', models.CharField(default='', max_length=60)),
                ('driving_school', models.ForeignKey(blank=True, limit_choices_to={'instructor_profile': None}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to='drivingSchool.drivingschool')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
