# Generated by Django 4.2.2 on 2023-07-14 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivingSchool', '0002_alter_drivingschool_companyname'),
        ('userProfile', '0002_alter_userprofile_driving_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='driving_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_profile', to='drivingSchool.drivingschool'),
        ),
    ]
