# Generated by Django 4.2.2 on 2023-07-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=254, null=True)),
                ('address', models.CharField(default='', max_length=254)),
                ('postal_code', models.CharField(max_length=8, null=True)),
                ('location_city', models.CharField(default='', max_length=254)),
                ('country', models.CharField(choices=[('CH', 'Switzerland'), ('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy')], max_length=2, null=True)),
            ],
        ),
    ]
